default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  username: news
  password: news123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: news_dev

test:
  <<: *default
  database: news_test
